spring.application.name=school

spring.datasource.url=jdbc:postgresql://localhost:5434/schooldb
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< HEAD

=======
>>>>>>> 34d5e488f18f7e6657e5c90be86721fb4d6fcde8
